import { translations } from "./i18n";
const extra = {
  en: {
    pdfQuality: "PDF image quality",
    pdfSourceQuality: "Source quality · keep image data",
    pdfPrintQuality: "Print 300 DPI · smaller file",
    pdfSourceHint:
      "Photo pixels and JPEG compression are kept unchanged. Identical photos are stored once in the PDF; only used fonts are embedded.",
    pdfPrintHint:
      "Excess photo resolution is reduced to 300 DPI for its largest printed placement, including zoom and bleed. Hidden crop areas are removed; JPEGs are encoded at high quality. This resizes images; it is not lossless compression. Photos in the project stay unchanged.",
    showPassword: "Show password",
    hidePassword: "Hide password",
    deletePageConfirm:
      "Delete this page? Following pages will move forward and an empty page will be added at the end. You can undo this.",
    fontHint:
      "10 free typefaces for English, Russian and Georgian. All allow commercial use.",
    pdfLayout: "PDF layout",
    pdfPages: "Individual A5 pages · recommended",
    pdfSpreads: "Facing spreads · reading order",
    pdfPagesHint:
      "Most printers accept individual pages and arrange them for their binding process. Send inside pages and covers separately when requested.",
    pdfSpreadsHint:
      "Facing pages 2–3, 4–5… on 296 × 210 mm spreads. First and last inside pages stay A5; no blank pages are added. Choose this if your printer requests reading-order spreads.",
    coverPrintHint:
      "The cover spread shows back / front without a spine. Hard-cover wrap and spine dimensions require the printer’s template.",
    spreadBleedHint:
      "302 × 216 mm spreads with 3 mm outer bleed. First/last inside pages: 154 × 216 mm. No extra bleed at the centre fold.",
    spreadNoBleed:
      "296 × 210 mm spreads; first/last inside pages: 148 × 210 mm. No bleed.",
    exportInfo:
      "RGB PDF with embedded fonts and high-resolution photographs. Confirm bleed, colour profile and binding requirements with your printer.",
    myBooks: "My books",
    account: "Sign in",
    logout: "Sign out",
    register: "Create account",
    login: "Sign in",
    email: "Email",
    password: "Password (at least 10 characters)",
    recover: "Recover access",
    recoveryCode: "Recovery code",
    recoveryIntro:
      "Save this code somewhere safe. It restores access if you forget your password. Email delivery is not configured.",
    downloadCode: "Download recovery code",
    continue: "Continue",
    newTitle: "A new story",
    create: "Create book",
    insidePages: "Inside pages",
    coversSeparate: "+ front and back covers",
    frontCover: "Front cover",
    backCover: "Back cover",
    insideCover: "Inside cover · not printed",
    coverSpread: "Cover layout · back / front",
    spread: "Spread",
    editText: "Edit text",
    text: "Text page",
    compact: "Condensed",
    textColor: "Text color",
    automaticColor: "Automatic color",
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    apply: "Apply",
    cancel: "Cancel",
    fill: "Fill frame",
    fit: "Fit whole photo",
    cropHint:
      "Drag a photo to crop it. Use + / −, the wheel or pinch to change its scale.",
    used: "Used",
    unused: "Unused only",
    printQuality: "Print quality",
    qualityTarget: "Recommended: 300 DPI",
    deleteBook: "Delete book",
    deleteConfirm: "Delete this book and its saved versions?",
    duplicateBook: "Make a copy",
    open: "Open book",
    localBooks: "On this device",
    cloudBooks: "Saved in your account",
    saveOnline: "Save in account",
    cloudSaved: "Saved in account",
    savingCloud: "Saving in account…",
    cloudError: "Could not save online. Your device has a draft.",
    saveVersion: "Save a version",
    versions: "Version history",
    versionName: "Version name (optional)",
    restore: "Restore",
    restoreConfirm:
      "Restore this version? The current book will remain in the version history.",
    automatic: "Autosave",
    manual: "Saved version",
    restored: "Restored version",
    noVersions: "No saved versions yet.",
    conflict:
      "This book changed on another device. Open its latest saved version or save your draft as a new book.",
    openLatest: "Open latest version",
    saveCopy: "Save as a new book",
    shrinkConfirm:
      "Reducing pages removes the last inside pages. A separate backup copy will be saved first. Continue?",
    backup: "Backup before reducing pages",
    moveTo: "Move selected page to",
    coverLocked: "Covers keep their positions",
    exportScope: "PDF pages",
    all: "Inside pages + covers",
    interior: "Inside pages only",
    covers: "Covers only",
    privacyCloud: "Account photos are private and saved on the server.",
    signInHint: "Sign in to save multiple books and versions online.",
    secureVersion: "Open secure studio",
    transfer: "Move this book to secure studio",
    transferHint: "Your original draft stays on this device.",
    transferFailed: "Open the secure studio and import the downloaded project.",
    authError:
      "Could not sign in. Check your email, password or recovery code.",
    error: "Something went wrong. Please try again.",
    emptyDashboard:
      "Your books will appear here. Start with 40, 60 or 80 pages.",
    demo: "Try a sample book",
    copies: "copies",
    welcome: "A home for your memories.",
    pageNumbers: "40 / 60 / 80 inside pages",
    versionSaved: "Version saved",
    restoredDone: "Version restored",
    noAccount: "Create an account",
    haveAccount: "Already have an account?",
    crop: "Crop photo",
    reset: "Reset crop",
    uploadHint: "JPG, PNG, WebP, HEIC · up to 30 MB",
    uploadError:
      "Some photos could not be decoded. Supported: JPG, PNG, WebP and HEIC up to 30 MB.",
    previewTitle: "Your book, spread by spread",
    prev: "Previous spread",
    next: "Next spread",
    localOnly: "A draft is saved on this device.",
    transferDone: "Book transferred. Sign in to save it in your account.",
    retry: "Retry saving",
    rename: "Book title",
    save: "Save",
    versionLimit: "50 named versions reached. Automatic saving still works.",
    quota:
      "Photo storage limit reached (1 GB). Download and delete old books to make room.",
    tooMany: "Too many attempts. Please try again later.",
    invalidPassword: "Use a password of at least 10 characters.",
    emailInUse: "An account with this email already exists.",
    busy: "Please wait…",
    saved: "Saved on this device",
  },
  ru: {
    pdfQuality: "Качество изображений PDF",
    pdfSourceQuality: "Исходное качество · без изменения фото",
    pdfPrintQuality: "Для печати 300 DPI · меньше файл",
    pdfSourceHint:
      "Пиксели и JPEG-сжатие фотографий сохраняются. Одинаковые фото хранятся в PDF один раз; встраиваются только используемые шрифты.",
    pdfPrintHint:
      "Избыточное разрешение фото уменьшается до 300 DPI для самого крупного размещения с учётом приближения и вылетов. Скрытые кадрированием области удаляются; JPEG сохраняется в высоком качестве. Это уменьшение изображений, а не сжатие без потерь. Фотографии в проекте не меняются.",
    showPassword: "Показать пароль",
    hidePassword: "Скрыть пароль",
    deletePageConfirm:
      "Удалить эту страницу? Следующие сдвинутся, а в конец добавится пустая страница. Действие можно отменить.",
    fontHint:
      "10 бесплатных шрифтов для английского, русского и грузинского. Все разрешены для коммерческого использования.",
    pdfLayout: "Формат PDF",
    pdfPages: "Постраничный A5 · рекомендуемый",
    pdfSpreads: "Развороты · в порядке чтения",
    pdfPagesHint:
      "Большинство типографий принимает отдельные страницы и делает спуск под своё оборудование и переплёт. По запросу выгружайте внутренние страницы и обложки отдельно.",
    pdfSpreadsHint:
      "Соседние страницы 2–3, 4–5… на разворотах 296 × 210 мм. Первая и последняя внутренние страницы остаются A5; пустые страницы не добавляются. Выбирайте, если типография просит развороты в порядке чтения.",
    coverPrintHint:
      "Разворот обложек: задняя / передняя, без корешка. Для твёрдого переплёта размеры корешка и загибов берутся из шаблона типографии.",
    spreadBleedHint:
      "Развороты 302 × 216 мм с внешними вылетами 3 мм. Первый/последний лист: 154 × 216 мм. В центре дополнительного вылета нет.",
    spreadNoBleed:
      "Развороты 296 × 210 мм; первый/последний лист: 148 × 210 мм. Без вылетов.",
    studio: "Студия фотокниг",
    tagline: "Истории, которые хочется сохранить.",
    myBooks: "Мои книги",
    account: "Войти",
    logout: "Выйти",
    register: "Создать аккаунт",
    login: "Войти",
    email: "Email",
    password: "Пароль (не менее 10 символов)",
    recover: "Восстановить доступ",
    recoveryCode: "Код восстановления",
    recoveryIntro:
      "Сохраните этот код в надёжном месте. Он позволит восстановить доступ, если вы забудете пароль. Отправка писем пока не подключена.",
    downloadCode: "Скачать код восстановления",
    continue: "Продолжить",
    newTitle: "Новая история",
    create: "Создать книгу",
    insidePages: "Страниц внутри",
    coversSeparate: "+ передняя и задняя обложки",
    frontCover: "Передняя обложка",
    backCover: "Задняя обложка",
    insideCover: "Внутри обложки · не печатается",
    coverSpread: "Обложки · задняя / передняя",
    spread: "Разворот",
    editText: "Редактировать текст",
    text: "Текстовая страница",
    compact: "Узкий",
    textColor: "Цвет текста",
    automaticColor: "Автоматический цвет",
    bold: "Жирный",
    italic: "Курсив",
    underline: "Подчёркнутый",
    apply: "Применить",
    cancel: "Отмена",
    fill: "Заполнить рамку",
    fit: "Фото целиком",
    cropHint:
      "Двигайте фото пальцем или мышью. Масштаб: + / −, колесо мыши или двумя пальцами.",
    used: "Использовано",
    unused: "Только неиспользованные",
    printQuality: "Качество печати",
    qualityTarget: "Рекомендуется 300 DPI",
    deleteBook: "Удалить книгу",
    deleteConfirm: "Удалить книгу и её сохранённые версии?",
    duplicateBook: "Создать копию",
    open: "Открыть книгу",
    localBooks: "На этом устройстве",
    cloudBooks: "Сохранено в аккаунте",
    saveOnline: "Сохранить в аккаунте",
    cloudSaved: "Сохранено в аккаунте",
    savingCloud: "Сохраняется в аккаунте…",
    cloudError: "Не удалось сохранить онлайн. Черновик есть на устройстве.",
    saveVersion: "Сохранить версию",
    versions: "История версий",
    versionName: "Название версии (необязательно)",
    restore: "Восстановить",
    restoreConfirm:
      "Восстановить эту версию? Текущая книга останется в истории.",
    automatic: "Автосохранение",
    manual: "Сохранённая версия",
    restored: "Восстановленная версия",
    noVersions: "Пока нет сохранённых версий.",
    conflict:
      "Книга изменилась на другом устройстве. Откройте последнюю версию или сохраните свой черновик как новую книгу.",
    openLatest: "Открыть последнюю",
    saveCopy: "Сохранить новой книгой",
    shrinkConfirm:
      "При уменьшении исчезнут последние внутренние страницы. Сначала сохраним отдельную резервную копию. Продолжить?",
    backup: "Копия перед уменьшением страниц",
    moveTo: "Переместить выбранную страницу на место",
    coverLocked: "Позиции обложек закреплены",
    exportScope: "Страницы PDF",
    all: "Внутренние страницы + обложки",
    interior: "Только внутренние страницы",
    covers: "Только обложки",
    privacyCloud:
      "Фотографии аккаунта сохраняются на сервере и доступны только вам.",
    signInHint: "Войдите, чтобы сохранять книги и версии онлайн.",
    secureVersion: "Открыть защищённую студию",
    transfer: "Перенести книгу в защищённую студию",
    transferHint: "Исходный черновик останется на этом устройстве.",
    transferFailed:
      "Откройте защищённую студию и импортируйте скачанный проект.",
    authError:
      "Не удалось войти. Проверьте email, пароль или код восстановления.",
    error: "Не удалось выполнить действие. Попробуйте ещё раз.",
    emptyDashboard:
      "Здесь появятся ваши книги. Начните с 40, 60 или 80 страниц.",
    demo: "Попробовать пример",
    copies: "раз",
    welcome: "Место для ваших воспоминаний.",
    pageNumbers: "40 / 60 / 80 страниц внутри",
    versionSaved: "Версия сохранена",
    restoredDone: "Версия восстановлена",
    noAccount: "Создать аккаунт",
    haveAccount: "Уже есть аккаунт?",
    crop: "Кадрировать фото",
    reset: "Сбросить кадрирование",
    uploadHint: "JPG, PNG, WebP, HEIC · до 30 МБ",
    uploadError:
      "Не удалось прочитать некоторые фото. Поддерживаются JPG, PNG, WebP и HEIC до 30 МБ.",
    previewTitle: "Ваша книга по разворотам",
    prev: "Предыдущий разворот",
    next: "Следующий разворот",
    localOnly: "Черновик сохраняется на этом устройстве.",
    transferDone: "Книга перенесена. Войдите, чтобы сохранить её в аккаунте.",
    retry: "Повторить сохранение",
    rename: "Название книги",
    save: "Сохранить",
    versionLimit:
      "Достигнут лимит 50 именованных версий. Автосохранение продолжает работать.",
    quota:
      "Достигнут лимит фотографий (1 ГБ). Скачайте и удалите старые книги, чтобы освободить место.",
    tooMany: "Слишком много попыток. Попробуйте позже.",
    invalidPassword: "Пароль должен содержать не менее 10 символов.",
    emailInUse: "Аккаунт с этим email уже существует.",
    busy: "Подождите…",
    saved: "Сохранено на устройстве",
    saving: "Сохраняется…",
    unsaved: "Не удалось сохранить на устройстве — скачайте проект",
    export: "Экспорт книги",
    photos: "Ваши фотографии",
    photoIntro: "Маленькие моменты. Большие воспоминания.",
    upload: "Загрузить фото",
    library: "Фототека",
    samples: "Примеры фотографий",
    sampleHint: "Замените примеры своими фотографиями.",
    placeHint: "Выберите рамку и нажмите на фото или перетащите его.",
    autoFill: "Заполнить пустые рамки",
    noPhotos: "Ваша история начинается с фотографии.",
    pages: "страниц",
    page: "Страница",
    moveLeft: "Переместить раньше",
    moveRight: "Переместить позже",
    preview: "Предпросмотр",
    layout: "Макет",
    caption: "Текст",
    styleTitle: "Оформление страницы",
    styleIntro: "Пространство для вашей истории.",
    pageLayout: "Макет страницы",
    pageColor: "Цвет бумаги",
    editorial: "Классический",
    full: "На весь лист",
    pair: "Два момента",
    diptych: "Рядом",
    grid: "Четыре истории",
    gallery: "Галерея",
    captionLabel: "Ваши слова",
    captionHint: "Место, дата, чувство…",
    typography: "Шрифт",
    serif: "Классический",
    sans: "Современный",
    fontSize: "Размер текста",
    alignment: "Выравнивание",
    left: "Слева",
    center: "По центру",
    right: "Справа",
    format: "A5 · 148 × 210 мм",
    portrait: "Вертикальная фотокнига",
    frame: "Рамка",
    empty: "Добавьте фотографию",
    zoomOut: "Уменьшить",
    zoomIn: "Увеличить",
    undo: "Отменить",
    redo: "Повторить",
    saveProject: "Скачать проект",
    openProject: "Открыть проект",
    newProject: "Новая книга",
    removePhoto: "Удалить фото",
    removeConfirm: "Удалить фото? Оно исчезнет со всех страниц.",
    printTitle: "Из воспоминаний — на бумагу.",
    printIntro: "Ваша книга готова к следующей главе.",
    exportInfo:
      "PDF в RGB со встроенными шрифтами и фотографиями высокого разрешения. Уточните вылеты, цветовой профиль и требования к переплёту у типографии.",
    bleed: "Вылеты 3 мм",
    bleedHint: "PDF 154 × 216 мм с областью обрезки A5.",
    noBleed: "PDF 148 × 210 мм без вылетов",
    review: "Проверка перед печатью",
    lowRes: "Низкое разрешение",
    emptyFrame: "Пустая рамка",
    good: "Качество всех фотографий подходит для печати.",
    warningAccept: "Я проверил предупреждения и хочу продолжить экспорт.",
    downloadPdf: "Скачать PDF для печати",
    exporting: "Готовим книгу…",
    done: "PDF готов.",
    close: "Закрыть",
    uploadBusy: "Добавляем фотографии…",
    importError:
      "Не удалось открыть проект. Выберите файл Matiane размером до 200 МБ.",
    exportError: "Не удалось создать PDF. Попробуйте ещё раз.",
    storageError: "Сохранение на устройстве недоступно. Скачайте проект.",
    projectSaved: "Проект скачан вместе с фотографиями.",
    privacy: "Ваши фотографии остаются в браузере.",
    blankBook: "Мои воспоминания",
    uploaded: "Фотографии добавлены",
    fillDone: "Пустые рамки заполнены",
    noFill: "Загрузите больше фотографий.",
    loaded: "Проект открыт",
    untitled: "Название книги",
    loading: "Открываем студию…",
    dpi: "DPI",
    photoLimit: "В книге может быть до 200 фотографий.",
    bleedFooter: "Печатайте в масштабе 100% · A5",
    captionFit: "Длинный текст автоматически уменьшается до размеров поля.",
    sampleWarning:
      "Примеры нужны для знакомства. Для печати используйте свои фото высокого разрешения.",
  },
  ka: {
    pdfQuality: "PDF-ის გამოსახულებების ხარისხი",
    pdfSourceQuality: "საწყისი ხარისხი · უცვლელი ფოტოები",
    pdfPrintQuality: "ბეჭდვისთვის 300 DPI · მცირე ფაილი",
    pdfSourceHint:
      "ფოტოს პიქსელები და JPEG-ის შეკუმშვა უცვლელია. ერთნაირი ფოტო PDF-ში ერთხელ ინახება; ჩაშენებულია მხოლოდ გამოყენებული შრიფტები.",
    pdfPrintHint:
      "ზედმეტი გარჩევადობა მცირდება 300 DPI-მდე ფოტოს ყველაზე დიდი საბეჭდი ზომისთვის, მასშტაბისა და ჩამონაჭრის გათვალისწინებით. კადრს გარეთ დამალული არეები იშლება; JPEG ინახება მაღალი ხარისხით. ეს გამოსახულების შემცირებაა და არა დანაკარგის გარეშე შეკუმშვა. პროექტში ფოტოები უცვლელი რჩება.",
    showPassword: "პაროლის ჩვენება",
    hidePassword: "პაროლის დამალვა",
    deletePageConfirm:
      "წავშალოთ ეს გვერდი? მომდევნო გვერდები წინ გადმოიწევს, ბოლოს კი ცარიელი გვერდი დაემატება. მოქმედების გაუქმება შესაძლებელია.",
    fontHint:
      "10 უფასო შრიფტი ინგლისური, რუსული და ქართული ტექსტისთვის. ყველა დაშვებულია კომერციული გამოყენებისთვის.",
    pdfLayout: "PDF-ის ფორმატი",
    pdfPages: "ცალკეული A5 გვერდები · რეკომენდებული",
    pdfSpreads: "გაშლილი გვერდები · კითხვის მიმდევრობით",
    pdfPagesHint:
      "სტამბების უმეტესობა იღებს ცალკეულ გვერდებს და თავად აწყობს საბეჭდ ფურცლებს აკინძვისთვის. მოთხოვნის შემთხვევაში შიდა გვერდები და ყდები ცალ-ცალკე გაიტანეთ.",
    pdfSpreadsHint:
      "მეზობელი გვერდები 2–3, 4–5… 296 × 210 მმ გაშლილ ფორმატში. პირველი და ბოლო შიდა გვერდი რჩება A5; ცარიელი გვერდები არ ემატება. გამოიყენეთ, თუ სტამბა ითხოვს გვერდებს კითხვის მიმდევრობით.",
    coverPrintHint:
      "ყდის განშლა: უკანა / წინა, ზურგის გარეშე. მყარი ყდის ზურგისა და გადაკეცვის ზომებისთვის საჭიროა სტამბის შაბლონი.",
    spreadBleedHint:
      "302 × 216 მმ განშლა, გარეთა კიდეებზე 3 მმ ჩამონაჭრით. პირველი/ბოლო გვერდი: 154 × 216 მმ. ცენტრში დამატებითი ჩამონაჭრი არ არის.",
    spreadNoBleed:
      "296 × 210 მმ განშლა; პირველი/ბოლო გვერდი: 148 × 210 მმ. ჩამონაჭრის გარეშე.",
    exportInfo:
      "RGB PDF ჩაშენებული შრიფტებითა და მაღალი გარჩევადობის ფოტოებით. ჩამონაჭრის, ფერის პროფილისა და აკინძვის მოთხოვნები შეათანხმეთ სტამბასთან.",
    myBooks: "ჩემი წიგნები",
    account: "შესვლა",
    logout: "გასვლა",
    register: "ანგარიშის შექმნა",
    login: "შესვლა",
    email: "ელფოსტა",
    password: "პაროლი (მინიმუმ 10 სიმბოლო)",
    recover: "წვდომის აღდგენა",
    recoveryCode: "აღდგენის კოდი",
    recoveryIntro:
      "შეინახეთ ეს კოდი უსაფრთხო ადგილას. ის დაგეხმარებათ პაროლის დავიწყებისას. ელფოსტით გაგზავნა ჯერ არ არის ჩართული.",
    downloadCode: "კოდის ჩამოტვირთვა",
    continue: "გაგრძელება",
    newTitle: "ახალი ამბავი",
    create: "წიგნის შექმნა",
    insidePages: "შიდა გვერდები",
    coversSeparate: "+ წინა და უკანა ყდები",
    frontCover: "წინა ყდა",
    backCover: "უკანა ყდა",
    insideCover: "ყდის შიდა მხარე · არ იბეჭდება",
    coverSpread: "ყდები · უკანა / წინა",
    spread: "გაშლილი გვერდები",
    editText: "ტექსტის რედაქტირება",
    text: "ტექსტის გვერდი",
    compact: "ვიწრო",
    textColor: "ტექსტის ფერი",
    automaticColor: "ავტომატური ფერი",
    bold: "მუქი",
    italic: "დახრილი",
    underline: "ხაზგასმული",
    apply: "გამოყენება",
    cancel: "გაუქმება",
    fill: "ჩარჩოს შევსება",
    fit: "მთლიანი ფოტო",
    cropHint:
      "გადააადგილეთ ფოტო. მასშტაბისთვის გამოიყენეთ + / −, მაუსის ბორბალი ან ორი თითი.",
    used: "გამოყენებულია",
    unused: "მხოლოდ გამოუყენებელი",
    printQuality: "ბეჭდვის ხარისხი",
    qualityTarget: "რეკომენდებულია: 300 DPI",
    deleteBook: "წიგნის წაშლა",
    deleteConfirm: "წაიშალოს წიგნი და მისი შენახული ვერსიები?",
    duplicateBook: "ასლის შექმნა",
    open: "წიგნის გახსნა",
    localBooks: "ამ მოწყობილობაზე",
    cloudBooks: "თქვენს ანგარიშში",
    saveOnline: "ანგარიშში შენახვა",
    cloudSaved: "შენახულია ანგარიშში",
    savingCloud: "ინახება ანგარიშში…",
    cloudError: "ონლაინ შენახვა ვერ მოხერხდა. მონახაზი მოწყობილობაზეა.",
    saveVersion: "ვერსიის შენახვა",
    versions: "ვერსიების ისტორია",
    versionName: "ვერსიის სახელი (არასავალდებულო)",
    restore: "აღდგენა",
    restoreConfirm: "აღდგეს ეს ვერსია? მიმდინარე წიგნი ისტორიაში დარჩება.",
    automatic: "ავტომატური შენახვა",
    manual: "შენახული ვერსია",
    restored: "აღდგენილი ვერსია",
    noVersions: "შენახული ვერსიები ჯერ არ არის.",
    conflict:
      "წიგნი სხვა მოწყობილობაზე შეიცვალა. გახსენით ბოლო ვერსია ან შეინახეთ მონახაზი ახალ წიგნად.",
    openLatest: "ბოლო ვერსიის გახსნა",
    saveCopy: "ახალ წიგნად შენახვა",
    shrinkConfirm:
      "შემცირებისას ბოლო შიდა გვერდები წაიშლება. ჯერ ცალკე სარეზერვო ასლი შეინახება. გაგრძელდეს?",
    backup: "ასლი გვერდების შემცირებამდე",
    moveTo: "არჩეული გვერდის გადატანა ნომერზე",
    coverLocked: "ყდების მდებარეობა უცვლელია",
    exportScope: "PDF-ის გვერდები",
    all: "შიდა გვერდები და ყდები",
    interior: "მხოლოდ შიდა გვერდები",
    covers: "მხოლოდ ყდები",
    privacyCloud: "ანგარიშის ფოტოები სერვერზე პირადად ინახება.",
    signInHint: "შედით წიგნებისა და ვერსიების ონლაინ შესანახად.",
    secureVersion: "დაცული სტუდიის გახსნა",
    transfer: "წიგნის გადატანა დაცულ სტუდიაში",
    transferHint: "ორიგინალი მონახაზი მოწყობილობაზე დარჩება.",
    transferFailed:
      "გახსენით დაცული სტუდია და შემოიტანეთ ჩამოტვირთული პროექტი.",
    authError:
      "შესვლა ვერ მოხერხდა. შეამოწმეთ ელფოსტა, პაროლი ან აღდგენის კოდი.",
    error: "ვერ შესრულდა. სცადეთ ხელახლა.",
    emptyDashboard:
      "აქ გამოჩნდება თქვენი წიგნები. დაიწყეთ 40, 60 ან 80 გვერდით.",
    demo: "სანიმუშო წიგნი",
    copies: "ჯერ",
    welcome: "სახლი თქვენი მოგონებებისთვის.",
    pageNumbers: "40 / 60 / 80 შიდა გვერდი",
    versionSaved: "ვერსია შეინახა",
    restoredDone: "ვერსია აღდგა",
    noAccount: "ანგარიშის შექმნა",
    haveAccount: "უკვე გაქვთ ანგარიში?",
    crop: "ფოტოს კადრირება",
    reset: "კადრირების აღდგენა",
    uploadHint: "JPG, PNG, WebP, HEIC · მაქს. 30 MB",
    uploadError:
      "ზოგი ფოტო ვერ გაიხსნა. მხარდაჭერილია JPG, PNG, WebP და HEIC, მაქს. 30 MB.",
    previewTitle: "თქვენი წიგნი გაშლილი გვერდებით",
    prev: "წინა გაშლა",
    next: "შემდეგი გაშლა",
    localOnly: "მონახაზი მოწყობილობაზე ინახება.",
    transferDone: "წიგნი გადატანილია. შედით მის ანგარიშში შესანახად.",
    retry: "შენახვის გამეორება",
    rename: "წიგნის სათაური",
    save: "შენახვა",
    versionLimit:
      "50 სახელდებული ვერსიის ლიმიტი. ავტომატური შენახვა გრძელდება.",
    quota:
      "ფოტოების ლიმიტი ამოიწურა (1 GB). ჩამოტვირთეთ და წაშალეთ ძველი წიგნები.",
    tooMany: "ძალიან ბევრი მცდელობაა. სცადეთ მოგვიანებით.",
    invalidPassword: "პაროლი მინიმუმ 10 სიმბოლოს უნდა შეიცავდეს.",
    emailInUse: "ამ ელფოსტით ანგარიში უკვე არსებობს.",
    busy: "დაელოდეთ…",
  },
};
export const messages = Object.fromEntries(
  ["en", "ka", "ru"].map((lang) => [
    lang,
    { ...translations.en, ...(translations[lang] || {}), ...extra[lang] },
  ]),
);
export function errorMessage(error, t) {
  return t[
    {
      email_in_use: "emailInUse",
      invalid_password: "invalidPassword",
      invalid_credentials: "authError",
      invalid_recovery: "authError",
      too_many_requests: "tooMany",
      storage_quota: "quota",
      version_conflict: "conflict",
      version_limit: "versionLimit",
    }[error.code] || "error"
  ];
}
